package co.edu.uniquindio.billeteravirtualfx.billeteravirtualfx.Controller;

import co.edu.uniquindio.billeteravirtualfx.billeteravirtualfx.Controller.Service.ITransaccionAdmControllerService;

public class TransaccionAdmController implements ITransaccionAdmControllerService{
}
